---
- debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value=true vtype=select

- apt_key: keyserver=keyserver.ubuntu.com id="{{ item }}" state=present
  with_items:
    - 7F0CEB10
    - 68576280

- apt_key: url="{{ item }}" state=present
  with_items:
    - https://packages.elastic.co/GPG-KEY-elasticsearch
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- apt_repository: repo="{{ item }}" state=present validate_certs=no
  with_items:
    - "ppa:webupd8team/java"
    - "ppa:ubuntugis/ubuntugis-unstable"
    - "deb https://deb.nodesource.com/node_5.x precise main"
    - "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse"

- copy: src="{{ item }}.list" dest="/etc/apt/sources.list.d/{{ item }}.list" owner=root mode=600
  with_items:
    - elasticsearch-2.x
    - nodesource

- apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - nodejs
    - gdal-bin
    - jq
    - mongodb-org=3.0.4
    - mongodb-org-server=3.0.4
    - mongodb-org-shell=3.0.4
    - mongodb-org-mongos=3.0.4
    - mongodb-org-tools=3.0.4
    - nginx-extras
    - unzip
    - oracle-java8-installer
    - elasticsearch

- alternatives: name=node path=/usr/bin/nodejs link=/usr/bin/node

- npm: path={{ app_dir }}
  become: vagrant

- npm: global=yes name=bower state=present

- shell: bower install chdir={{ app_dir }}
  become: vagrant